Sanitize HTML from crawled event descriptions
codeformuenster/muenster-jetzt pull request #230
Opened 2020-09-22 09:01 UTC by jdemaeyer

Related: #227

2020-09-22 19:43 UTC, ThorbenJensen requested changes

2020-09-22 19:43 UTC, ThorbenJensen commented on backend/mj/spiders/__init__.py
> +    SANITIZE_FIELDS = ['description']
```suggestion
    SANITIZE_FIELDS = ['description']  # list of event fields to be sanitized
```

2020-09-22 19:43 UTC, ThorbenJensen commented on backend/mj/spiders/__init__.py
> +
```suggestion
    """For security, escapes or removes all html tags from chosen fields, e.g. event description."""
    
```

does this docstring describe what's happening?

2020-09-23 06:19 UTC, bCyberBasti commented
A Note on this before the call this evening: in the frontend we do sanitize the html and render the safe parts like e.g. a line break.. if we serve a sanitized version we should not completely discard that information because it has some value.
One idea: 
- simply prefix all fields with unsafe content to e.g. `unsafe_description` to warn a dev that the field needs some precaution on usage.
- additionally we could provide a safe version of those fields with data that is sanitized by our api (if performance allows this we could think of not storing that information in the database but do this on the fly?)

2020-09-23 12:40 UTC, bCyberBasti commented
forget my comment from above.. i now had the time to take a look into bleach and got the reasoning behind it (i somehow managed to think that bleach will just remove every html 🙈 ) 

@jdemaeyer this looks good 👍  and for now I see no reason to store any additional raw "nonsense" 😄 
will approve this PR in a few seconds, feel free to merge it after you handled the suggestions from @ThorbenJensen

2020-09-23 12:41 UTC, bCyberBasti approved these changes

2020-09-23 13:01 UTC, ubergesundheit commented on backend/mj/spiders/__init__.py
> +    SANITIZE_FIELDS = ['description']
Why not sanitize more (or even all) fields ?

2020-09-23 17:03 UTC, ubergesundheit commented
We just decided we want to keep the following tags:

- i
- b & strong
- br
- p (but not nested)
- ul & li
- a (with target="_blank" & rel="noopener noreferrer")

2020-10-02 14:49 UTC, jdemaeyer commented on backend/mj/spiders/__init__.py
> +    SANITIZE_FIELDS = ['description']
We currently "know" aka assume that crawled items will only contain HTML in the `description` field.

If there is HTML in any of the other fields there is either a bug in one of our spiders or one of the assumptions we made when writing that spider turned out to be wrong. In both cases I prefer that we faceplant hard rather than automagically und unknowingly maybe-maybe-not fix it by applying bleach to all fields. I've made this more explicit via fb27218

2020-10-02 14:50 UTC, jdemaeyer commented on backend/mj/spiders/__init__.py
> +
Yep, added via fb27218

2020-10-02 14:54 UTC, jdemaeyer commented
> We just decided we want to keep the following tags:

If we _do_ want to keep some tags I suggest we indeed add a new field `formatted_description` (or similar) with the HTML-ized description and keep the `description` field HTML-free, so we don't push down sanitizing HTML to users who need clean text.

Can we live with dropping the "but not nested" and "a target/rel" requirements? Those are not straight-forward via `bleach` (we can easily remove any `target`/`rel` attributes, just not override them).

2020-10-02 14:59 UTC, jdemaeyer commented
Blocked by #236

Will rebase once that's merged

2020-10-02 15:31 UTC, ubergesundheit commented
> If we do want to keep some tags I suggest we indeed add a new field formatted_description (or similar) with the HTML-ized description and keep the description field HTML-free, so we don't push down sanitizing HTML to users who need clean text.

Sounds reasonable. Let clients decide which field to consume.

> Can we live with dropping the "but not nested" and "a target/rel" requirements? Those are not straight-forward via bleach (we 
can easily remove any target/rel attributes, just not override them).

Is it possible to keep just the string between the `<a...>this one</a>` tags? I would rather have this than someone rouge upstream linking some porn sites or something else.

2020-10-02 15:32 UTC, ubergesundheit commented
> Will rebase once that's merged

Please don't rebase. This makes it harder for everyone else following work done in a branch locally

2020-10-05 20:21 UTC, ThorbenJensen approved these changes
code-wise looks good.
but regarding the detailed logic of sanitization, i am not the right person to ask.

2020-10-10 09:29 UTC, jdemaeyer commented
Sorry for being so slow on this. I've updated the PR with a migration adding the `formatted_description` field and scraping logic to fill it. These tags are kept:

- `b`
- `br`
- `em`
- `i`
- `li`
- `p` (even nested)
- `span`
- `strong`
- `ul`

All other tags are stripped but their text content is kept (i.e. `<a href="...">link text</a>` is converted to `link text`). `description` is still completely free of HTML tags.

The resulting `formatted_description` is not 100 % perfect (e.g. empty paragraphs from the source `<p>Some text</p><p></p><p></p>` are kept as is) but probably as close as we can get without adding a ton of special case handling.

@ubergesundheit can you add the updated API client pretty-please?

2020-10-10 11:08 UTC, ubergesundheit commented
Very nice! One little thing: Could you add a human readable description to the old and new field to be displayed in the `/docs` page?

I know the api client needs to be regenerated again, but thats easy. (But you probably already know this)

Start the backend (does not need a database)

```
# in the frontend directory
docker run --rm -it -v $(pwd):/app -u $(id -u) --network host --entrypoint bash --workdir /app node:14 -c "npm install && npm run generate-client"
```

2020-10-10 11:55 UTC, ubergesundheit approved these changes
Absolutely fantastic

2020-10-10 11:56 UTC, jdemaeyer commented
Sure, added!

This PR is ready-to-merge from my side. I'll be gone for the rest of the weekend so feel free to merge

2020-10-10 12:14 UTC, merged